apiVersion: apps/v1
kind: Deployment
metadata:
  name: IDP
  labels:
    app: IDP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IDP
  template:
    metadata:
      labels:
        app: IDP
    spec:
      containers:
        - name: IDP
          image: 160721459527.dkr.ecr.eu-central-1.amazonaws.com/idp:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080